{{/*
=============================================================================
ServiceAccount
=============================================================================
A ServiceAccount provides an identity for pods.

For .NET Developers:
- Similar to an "Application Identity" in Azure AD
- Pods use this identity to access Kubernetes API
- Can be mapped to cloud IAM roles (AWS IRSA, GCP Workload Identity)
=============================================================================
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fundamental-stack.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fundamental-stack.backend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
